# Generated by Django 4.2.4 on 2023-09-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_docsstructuremodel_parent_struct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('level', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='docs.documentcategories')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentsmodel',
            name='structure',
        ),
        migrations.DeleteModel(
            name='DocsStructureModel',
        ),
        migrations.AddField(
            model_name='documentsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.documentcategories'),
        ),
    ]
