# Generated by Django 4.2.4 on 2023-09-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_documentcategories_remove_documentsmodel_structure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentCategories',
            new_name='DocumentCategoriesModel',
        ),
    ]
