# Generated by Django 4.2.4 on 2023-09-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_rename_documentcategories_documentcategoriesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=40)),
                ('field_type', models.CharField(max_length=40)),
                ('field_label', models.CharField(max_length=60)),
                ('field_validator', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocsFormLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.documentsmodel')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.dynamicformmodel')),
            ],
        ),
    ]
